# Use an official Python runtime as a parent image
FROM ubuntu:16.04

## Install any needed packages specified in requirements.txt
#RUN apt-get update
#RUN apt-get install -y --force-yes build-essential golang

# Make port 80 available to the world outside this container
EXPOSE 8545 8546 30303 30303/udp
